// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTN7Neg_mgzoqJ7YAtkpX9JYPig1Y-h8',
    appId: '1:1022091343603:web:6090d55e5341eb6e61a986',
    messagingSenderId: '1022091343603',
    projectId: 'mailgpt-47c2f',
    authDomain: 'mailgpt-47c2f.firebaseapp.com',
    storageBucket: 'mailgpt-47c2f.firebasestorage.app',
    measurementId: 'G-482T0HG8G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VJ-Y3tXwS9PjBORqxxBQJ7EDNXOue3Q',
    appId: '1:1022091343603:android:24fd12fa990d1faa61a986',
    messagingSenderId: '1022091343603',
    projectId: 'mailgpt-47c2f',
    storageBucket: 'mailgpt-47c2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0IcHWzbO2f-IMOQ9lOs1Vhpa--pPD0gs',
    appId: '1:1022091343603:ios:6fed4aae735de35a61a986',
    messagingSenderId: '1022091343603',
    projectId: 'mailgpt-47c2f',
    storageBucket: 'mailgpt-47c2f.firebasestorage.app',
    iosBundleId: 'com.example.mailgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0IcHWzbO2f-IMOQ9lOs1Vhpa--pPD0gs',
    appId: '1:1022091343603:ios:6fed4aae735de35a61a986',
    messagingSenderId: '1022091343603',
    projectId: 'mailgpt-47c2f',
    storageBucket: 'mailgpt-47c2f.firebasestorage.app',
    iosBundleId: 'com.example.mailgpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkTN7Neg_mgzoqJ7YAtkpX9JYPig1Y-h8',
    appId: '1:1022091343603:web:e7ce85624489944061a986',
    messagingSenderId: '1022091343603',
    projectId: 'mailgpt-47c2f',
    authDomain: 'mailgpt-47c2f.firebaseapp.com',
    storageBucket: 'mailgpt-47c2f.firebasestorage.app',
    measurementId: 'G-DDRWVKF2MD',
  );
}
